#:import utils kivy.utils

<Box>
    BoxLayout:
        orientation:"vertical"
        size: root.width, root.height
        TextInput:
            id: display_result
            text: "0"
            foreground_color: utils.get_color_from_hex("#FF6600")
            halign: "right"
            background_color: utils.get_color_from_hex("#262626")
            font_size: 62
            size_hint: (1, 0.3)

        GridLayout:
            cols: 4
            row: 5


            Button:
                id: btn
                text: "AC"
                font_size: 38
                background_normal: ''
                background_color: utils. get_color_from_hex("#262626")
                color: utils.get_color_from_hex("#FF6600")
                on_press:root.clear()


            Button:
                id: btn
                text: "<"
                font_size: 38
                background_normal: ''
                background_color: utils. get_color_from_hex("#262626")
                color: utils.get_color_from_hex("#FF6600")
                on_press: root.CE()

            Button:
                id: btn
                text: "%"
                font_size: 38
                background_normal: ''
                background_color: utils. get_color_from_hex("#262626")
                color: utils.get_color_from_hex("#FF6600")
                on_press: root.show("%")

            Button:
                id: btn
                text: "÷"
                font_size: 38
                background_normal: ''
                background_color: utils. get_color_from_hex("#262626")
                color: utils.get_color_from_hex("#FF6600")
                on_press: root.show('/')


            Button:
                id: btn
                text: "7"
                font_size: 38
                background_color: utils. get_color_from_hex("#262626")
                on_press: root.show('7')

            Button:
                id: btn
                text: "8"
                font_size: 38
                background_color: utils. get_color_from_hex("#262626")
                on_press: root.show('8')

            Button:
                id: btn
                text: "9"
                font_size: 38
                background_color: utils. get_color_from_hex("#262626")
                on_press: root.show('9')

            Button:
                id: btn
                text: "*"
                font_size: 38
                background_normal: ''
                background_color: utils. get_color_from_hex("#262626")
                color: utils.get_color_from_hex("#FF6600")
                on_press: root.show('*')


            Button:
                id: btn
                text: "4"
                font_size: 38
                background_color: utils. get_color_from_hex("#262626")
                on_press: root.show('4')

            Button:
                id: btn
                text: "5"
                font_size: 38
                background_color: utils. get_color_from_hex("#262626")
                on_press: root.show('5')

            Button:
                id: btn
                text: "6"
                font_size: 38
                background_color: utils. get_color_from_hex("#262626")
                on_press: root.show('6')

            Button:
                id: btn
                text: "-"
                font_size: 38
                background_normal: ''
                background_color: utils. get_color_from_hex("#262626")
                color: utils.get_color_from_hex("#FF6600")
                on_press: root.show('-')


            Button:
                id: btn
                text: "1"
                font_size: 38
                background_color: utils. get_color_from_hex("#262626")
                on_press: root.show('1')

            Button:
                id: btn
                text: "2"
                font_size: 38
                background_color: utils. get_color_from_hex("#262626")
                on_press: root.show('2')

            Button:
                id: btn
                text: "3"
                font_size: 38
                background_color: utils. get_color_from_hex("#262626")
                on_press: root.show('3')

            Button:
                id: btn
                text: "+"
                font_size: 38
                background_normal: ''
                background_color: utils. get_color_from_hex("#262626")
                color: utils.get_color_from_hex("#FF6600")
                on_press: root.show('+')


            Button:
                id: btn
                text: "0"
                font_size: 38
                background_color: utils. get_color_from_hex("#262626")
                on_press: root.show('0')

            Button:
                id: btn
                text: "00"
                font_size: 38
                background_color: utils. get_color_from_hex("#262626")
                on_press: root.show('00')

            Button:
                id: btn
                text: "."
                font_size: 38
                background_normal: ''
                background_color: utils. get_color_from_hex("#262626")
                color: utils.get_color_from_hex("#FF6600")
                on_press: root.show('.')

            Button:
                id: btn
                text: "="
                font_size: 38
                background_normal: ''
                background_color: utils. get_color_from_hex("#FF6600")
                color: utils.get_color_from_hex("#262626")
                on_press: root.equal()
